name: "Build"
on:
  pull_request:
  push:
  workflow_run:
    workflows: ["Update Flake Hash"]
    types:
      - completed
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: cachix/install-nix-action@v30
      with:
        extra_nix_config: extra-experimental-features = pipe-operators nix-command flakes
        github_access_token: ${{ secrets.GITHUB_TOKEN }}
    - run: nix build
    - run: nix flake check